### ISSUE TITLE
Update to play-2.6

### ISSUE THREAD

**Issue by fancywriter** [wsargent/play-2.5.x-scala-compile-di-with-tests#42]
Would be great to see up-to-date version of this nice example!

**Comment by gmethvin** [comment]
It is updated: https://github.com/playframework/play-scala-compile-di-example/blob/2.6.x/project/plugins.sbt#L2

Does it not work for you?

**Comment by fancywriter** [comment]
Oh, sorry, looks like google pointed me to the wrong branch. 🤓
