### ISSUE TITLE
BuiltInComponents.global is deprecated in MyComponents

### ISSUE THREAD

**Issue by loicknuchel** [wsargent/play-2.5.x-scala-compile-di-with-tests#6]
Hi,

First, thanks A LOT for this very valuable tutorial (I couldn't test my controllers without it).

Following it I saw that BuiltInComponents.global was deprecated with the mention "Use dependency injection" for Play 2.5.x but I can't figure out how to update the code to not use it anymore...

Do you have any idea ?

**Comment by gmethvin** [comment]
@loicknuchel How to remove `GlobalSettings` is described in the Play 2.4 migration guide: https://www.playframework.com/documentation/2.5.x/GlobalSettings

If you have any other questions the best place to ask is on the [mailing list](https://groups.google.com/forum/#!forum/play-framework). This is a bug tracker for reporting issues with this particular template.

**Comment by loicknuchel** [comment]
Thanks for your quick response and sorry for the inconvenience.
